In [205]:
import numpy as np
data = open('input.txt').read().split("\n")
data = [np.array([int(x) for x in row]) for row in data]
data = data[:-1]
# import numpy as np
data = np.vstack(data)
data

array([[0, 1, 1, ..., 0, 0, 1],
       [1, 0, 2, ..., 2, 2, 0],
       [0, 0, 2, ..., 0, 2, 0],
       ...,
       [1, 2, 2, ..., 0, 2, 0],
       [2, 2, 1, ..., 0, 1, 1],
       [2, 0, 2, ..., 1, 2, 0]])

In [206]:
visible_mask = np.ones(data.shape)

In [207]:
data.shape

(99, 99)

In [208]:
right

array([9])

In [209]:
( value<= top).sum()>1

False

In [210]:
for i in range(data.shape[0]-1):
    for j in range(data.shape[1]-1):
        #check left
        try:
            value = data[i,j]
            left = data[i,:j]
            right = data[i,j+1:]
            top = data[:i,j]
            bottom = data[i+1:,j]
            if( value<= left).sum()>0:
                if ( value<= top).sum()>0:
                    if( value<= right).sum()>0:
                        if ( value<= bottom).sum()>0:
                            visible_mask[i,j] = 0
                            print("HERE",i,j)
        except:
            print("ERROR",i,j)

HERE 1 1
HERE 1 3
HERE 1 4
HERE 1 5
HERE 1 8
HERE 1 11
HERE 1 12
HERE 1 13
HERE 1 15
HERE 1 16
HERE 1 17
HERE 1 19
HERE 1 21
HERE 1 22
HERE 1 26
HERE 1 27
HERE 1 30
HERE 1 31
HERE 1 33
HERE 1 36
HERE 1 39
HERE 1 41
HERE 1 43
HERE 1 49
HERE 1 51
HERE 1 53
HERE 1 55
HERE 1 60
HERE 1 65
HERE 1 66
HERE 1 67
HERE 1 69
HERE 1 75
HERE 1 77
HERE 1 80
HERE 1 81
HERE 1 87
HERE 1 89
HERE 1 90
HERE 1 91
HERE 1 92
HERE 1 93
HERE 1 94
HERE 1 95
HERE 2 1
HERE 2 3
HERE 2 6
HERE 2 9
HERE 2 12
HERE 2 13
HERE 2 14
HERE 2 15
HERE 2 16
HERE 2 18
HERE 2 19
HERE 2 20
HERE 2 21
HERE 2 23
HERE 2 24
HERE 2 25
HERE 2 26
HERE 2 28
HERE 2 29
HERE 2 30
HERE 2 32
HERE 2 34
HERE 2 35
HERE 2 38
HERE 2 39
HERE 2 40
HERE 2 41
HERE 2 43
HERE 2 44
HERE 2 45
HERE 2 46
HERE 2 49
HERE 2 50
HERE 2 52
HERE 2 53
HERE 2 54
HERE 2 55
HERE 2 56
HERE 2 57
HERE 2 58
HERE 2 60
HERE 2 61
HERE 2 62
HERE 2 63
HERE 2 64
HERE 2 67
HERE 2 69
HERE 2 70
HERE 2 71
HERE 2 72
HERE 2 73
HERE 2 74
HERE 2 75
HERE 2 76
HERE 2 77
HERE 2 79
HERE 2 80

HERE 17 36
HERE 17 37
HERE 17 39
HERE 17 40
HERE 17 41
HERE 17 42
HERE 17 43
HERE 17 44
HERE 17 45
HERE 17 46
HERE 17 47
HERE 17 49
HERE 17 51
HERE 17 53
HERE 17 54
HERE 17 55
HERE 17 56
HERE 17 57
HERE 17 59
HERE 17 60
HERE 17 61
HERE 17 63
HERE 17 64
HERE 17 65
HERE 17 66
HERE 17 67
HERE 17 68
HERE 17 69
HERE 17 70
HERE 17 71
HERE 17 72
HERE 17 73
HERE 17 74
HERE 17 75
HERE 17 76
HERE 17 78
HERE 17 79
HERE 17 80
HERE 17 81
HERE 17 82
HERE 17 83
HERE 17 84
HERE 17 85
HERE 17 86
HERE 17 87
HERE 17 89
HERE 17 90
HERE 17 91
HERE 17 92
HERE 17 93
HERE 17 94
HERE 17 97
HERE 18 1
HERE 18 2
HERE 18 3
HERE 18 5
HERE 18 6
HERE 18 7
HERE 18 8
HERE 18 9
HERE 18 10
HERE 18 11
HERE 18 12
HERE 18 13
HERE 18 14
HERE 18 15
HERE 18 16
HERE 18 18
HERE 18 19
HERE 18 20
HERE 18 21
HERE 18 22
HERE 18 23
HERE 18 24
HERE 18 25
HERE 18 26
HERE 18 27
HERE 18 28
HERE 18 29
HERE 18 30
HERE 18 31
HERE 18 32
HERE 18 33
HERE 18 35
HERE 18 37
HERE 18 38
HERE 18 39
HERE 18 41
HERE 18 42
HERE 18 44
HERE 18 45
HERE 18

HERE 32 50
HERE 32 51
HERE 32 55
HERE 32 58
HERE 32 59
HERE 32 60
HERE 32 61
HERE 32 62
HERE 32 63
HERE 32 64
HERE 32 65
HERE 32 66
HERE 32 67
HERE 32 68
HERE 32 69
HERE 32 71
HERE 32 72
HERE 32 73
HERE 32 75
HERE 32 76
HERE 32 77
HERE 32 78
HERE 32 79
HERE 32 81
HERE 32 82
HERE 32 83
HERE 32 84
HERE 32 85
HERE 32 86
HERE 32 88
HERE 32 89
HERE 32 90
HERE 32 91
HERE 32 92
HERE 32 93
HERE 32 94
HERE 32 95
HERE 32 97
HERE 33 2
HERE 33 3
HERE 33 4
HERE 33 6
HERE 33 7
HERE 33 8
HERE 33 10
HERE 33 11
HERE 33 14
HERE 33 15
HERE 33 16
HERE 33 17
HERE 33 18
HERE 33 19
HERE 33 21
HERE 33 22
HERE 33 23
HERE 33 24
HERE 33 25
HERE 33 26
HERE 33 30
HERE 33 31
HERE 33 32
HERE 33 33
HERE 33 34
HERE 33 35
HERE 33 36
HERE 33 37
HERE 33 39
HERE 33 40
HERE 33 41
HERE 33 42
HERE 33 43
HERE 33 44
HERE 33 45
HERE 33 46
HERE 33 47
HERE 33 49
HERE 33 50
HERE 33 51
HERE 33 52
HERE 33 53
HERE 33 54
HERE 33 55
HERE 33 58
HERE 33 59
HERE 33 60
HERE 33 61
HERE 33 62
HERE 33 63
HERE 33 64
HERE 33 65
HERE 33 66
HERE 

HERE 48 52
HERE 48 53
HERE 48 54
HERE 48 55
HERE 48 56
HERE 48 57
HERE 48 58
HERE 48 59
HERE 48 60
HERE 48 62
HERE 48 63
HERE 48 64
HERE 48 65
HERE 48 66
HERE 48 67
HERE 48 69
HERE 48 70
HERE 48 71
HERE 48 72
HERE 48 73
HERE 48 74
HERE 48 75
HERE 48 76
HERE 48 77
HERE 48 78
HERE 48 79
HERE 48 80
HERE 48 81
HERE 48 82
HERE 48 84
HERE 48 85
HERE 48 86
HERE 48 87
HERE 48 88
HERE 48 89
HERE 48 90
HERE 48 92
HERE 48 93
HERE 48 94
HERE 48 95
HERE 48 96
HERE 48 97
HERE 49 1
HERE 49 2
HERE 49 3
HERE 49 4
HERE 49 5
HERE 49 6
HERE 49 8
HERE 49 10
HERE 49 11
HERE 49 12
HERE 49 13
HERE 49 14
HERE 49 15
HERE 49 16
HERE 49 18
HERE 49 19
HERE 49 20
HERE 49 21
HERE 49 22
HERE 49 24
HERE 49 25
HERE 49 26
HERE 49 27
HERE 49 28
HERE 49 29
HERE 49 30
HERE 49 31
HERE 49 32
HERE 49 33
HERE 49 35
HERE 49 36
HERE 49 37
HERE 49 38
HERE 49 39
HERE 49 40
HERE 49 41
HERE 49 42
HERE 49 43
HERE 49 44
HERE 49 45
HERE 49 46
HERE 49 47
HERE 49 48
HERE 49 49
HERE 49 50
HERE 49 51
HERE 49 52
HERE 49 53
HERE 49 54
HERE 4

HERE 62 24
HERE 62 25
HERE 62 26
HERE 62 28
HERE 62 29
HERE 62 30
HERE 62 31
HERE 62 32
HERE 62 33
HERE 62 34
HERE 62 35
HERE 62 36
HERE 62 37
HERE 62 39
HERE 62 40
HERE 62 41
HERE 62 42
HERE 62 43
HERE 62 44
HERE 62 45
HERE 62 46
HERE 62 47
HERE 62 48
HERE 62 49
HERE 62 51
HERE 62 52
HERE 62 53
HERE 62 54
HERE 62 55
HERE 62 56
HERE 62 57
HERE 62 58
HERE 62 59
HERE 62 60
HERE 62 61
HERE 62 62
HERE 62 64
HERE 62 65
HERE 62 66
HERE 62 67
HERE 62 68
HERE 62 69
HERE 62 70
HERE 62 71
HERE 62 72
HERE 62 73
HERE 62 74
HERE 62 75
HERE 62 76
HERE 62 78
HERE 62 79
HERE 62 80
HERE 62 81
HERE 62 84
HERE 62 85
HERE 62 86
HERE 62 87
HERE 62 88
HERE 62 89
HERE 62 90
HERE 62 91
HERE 62 92
HERE 62 93
HERE 62 94
HERE 62 95
HERE 62 96
HERE 62 97
HERE 63 2
HERE 63 4
HERE 63 5
HERE 63 6
HERE 63 7
HERE 63 8
HERE 63 9
HERE 63 10
HERE 63 12
HERE 63 13
HERE 63 14
HERE 63 15
HERE 63 16
HERE 63 17
HERE 63 18
HERE 63 19
HERE 63 20
HERE 63 21
HERE 63 22
HERE 63 23
HERE 63 24
HERE 63 26
HERE 63 27
HERE 63 28
HERE 6

HERE 75 51
HERE 75 52
HERE 75 53
HERE 75 54
HERE 75 55
HERE 75 56
HERE 75 57
HERE 75 58
HERE 75 59
HERE 75 60
HERE 75 61
HERE 75 62
HERE 75 63
HERE 75 65
HERE 75 66
HERE 75 67
HERE 75 68
HERE 75 70
HERE 75 71
HERE 75 72
HERE 75 73
HERE 75 74
HERE 75 75
HERE 75 76
HERE 75 77
HERE 75 79
HERE 75 80
HERE 75 81
HERE 75 82
HERE 75 83
HERE 75 84
HERE 75 85
HERE 75 86
HERE 75 88
HERE 75 89
HERE 75 90
HERE 75 91
HERE 75 92
HERE 75 93
HERE 75 94
HERE 75 95
HERE 75 96
HERE 75 97
HERE 76 1
HERE 76 2
HERE 76 3
HERE 76 5
HERE 76 6
HERE 76 7
HERE 76 8
HERE 76 9
HERE 76 10
HERE 76 11
HERE 76 12
HERE 76 14
HERE 76 15
HERE 76 16
HERE 76 17
HERE 76 18
HERE 76 19
HERE 76 21
HERE 76 22
HERE 76 23
HERE 76 24
HERE 76 25
HERE 76 27
HERE 76 28
HERE 76 29
HERE 76 30
HERE 76 31
HERE 76 32
HERE 76 33
HERE 76 34
HERE 76 36
HERE 76 37
HERE 76 38
HERE 76 40
HERE 76 41
HERE 76 42
HERE 76 44
HERE 76 45
HERE 76 46
HERE 76 50
HERE 76 51
HERE 76 52
HERE 76 53
HERE 76 54
HERE 76 57
HERE 76 58
HERE 76 59
HERE 76 61
HERE 76

HERE 90 9
HERE 90 10
HERE 90 11
HERE 90 12
HERE 90 13
HERE 90 15
HERE 90 16
HERE 90 17
HERE 90 18
HERE 90 19
HERE 90 20
HERE 90 21
HERE 90 22
HERE 90 24
HERE 90 25
HERE 90 26
HERE 90 27
HERE 90 28
HERE 90 29
HERE 90 30
HERE 90 31
HERE 90 32
HERE 90 34
HERE 90 37
HERE 90 38
HERE 90 39
HERE 90 41
HERE 90 42
HERE 90 43
HERE 90 44
HERE 90 45
HERE 90 46
HERE 90 47
HERE 90 48
HERE 90 49
HERE 90 50
HERE 90 51
HERE 90 52
HERE 90 54
HERE 90 56
HERE 90 57
HERE 90 58
HERE 90 59
HERE 90 60
HERE 90 61
HERE 90 62
HERE 90 63
HERE 90 64
HERE 90 65
HERE 90 67
HERE 90 68
HERE 90 69
HERE 90 70
HERE 90 71
HERE 90 72
HERE 90 73
HERE 90 74
HERE 90 75
HERE 90 76
HERE 90 77
HERE 90 80
HERE 90 81
HERE 90 82
HERE 90 83
HERE 90 84
HERE 90 85
HERE 90 86
HERE 90 87
HERE 90 88
HERE 90 90
HERE 90 91
HERE 90 92
HERE 90 93
HERE 90 94
HERE 90 95
HERE 91 2
HERE 91 3
HERE 91 4
HERE 91 5
HERE 91 6
HERE 91 7
HERE 91 8
HERE 91 9
HERE 91 11
HERE 91 12
HERE 91 13
HERE 91 14
HERE 91 15
HERE 91 16
HERE 91 17
HERE 91 18
HERE 91 

In [211]:
visible_mask.sum()

1845.0

In [212]:
data

array([[0, 1, 1, ..., 0, 0, 1],
       [1, 0, 2, ..., 2, 2, 0],
       [0, 0, 2, ..., 0, 2, 0],
       ...,
       [1, 2, 2, ..., 0, 2, 0],
       [2, 2, 1, ..., 0, 1, 1],
       [2, 0, 2, ..., 1, 2, 0]])

In [213]:
scenic_score = np.zeros(data.shape)

In [216]:
for i in range(1,data.shape[0]-1):
    for j in range(1, data.shape[1]-1):
        value = data[i,j]
        left = data[i,:j]
        right = data[i,j+1:]
        top = data[:i,j]
        bottom = data[i+1:,j]
        
        
        if (value<= left).sum()>0:
            left_val = len(left)-(np.where(left >= value)[0].max())
        else:
            left_val = len(left)
        
        if (value<= top).sum()>0:
            top_val = len(top)-(np.where(top >= value)[0].max())
        else:
            top_val = len(top)
        if (value<= right).sum()>0:
            right_val =np.where(right >= value)[0].min()+1
        else:
            right_val = len(right)
        if (value<= bottom).sum()>0:
            bot_val =np.where(bottom >= value)[0].min()+1
        else:
            bot_val = len(bottom)
#         print(i,j,"", right_val,left_val,top_val,bot_val)
        ss = right_val*left_val*top_val*bot_val
        scenic_score[i,j] = ss


In [217]:
scenic_score.max()

230112.0